import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
import { Header } from "@/components"

export const metadata: Metadata = {
  title: 'Edvaldo Raw',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  lang,
}: {
  children: React.ReactNode;
  lang: 'en'|'pt';
}) {
  const fontClass = lang === 'en'? 'font-freight-en': 'font-freight-pt';
  return (
    <html lang={lang}>
      <body className="font-freight">
        <Header />
        {children}
      </body>
    </html>
  )
}
