import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components"; 
import { notFound } from "next/navigation";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Edvaldo Raw",
  description: "Generated by create next app",
};

const locales = ["en", "pt"];

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale)) {
    notFound();
  }
  const messages = useMessages();
  {
    return (
      <html lang={locale}>
        <body className="font-freight">
        <NextIntlClientProvider messages={messages}>
        <Header />
          {children}
        </NextIntlClientProvider>
        </body>
      </html>
    );
  }
}
